version: '3'

services:
  backup:
    build: .
    image: local/backup:alpine
    container_name: backup_container
    environment:
      env_file: .env
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ${DATA_PATH}:/data:ro
    restart: always
