#!/bin/sh
set -euo pipefail

# Script that creates an encrypted Borg backup and
# uploads the backup in a cloud storage through rclone.
#
# Requirements:
# - Configure a Borg repository before launching this command
# - Configure rclone and create a valid cloud storage (e.g. AWS Glacier)
#
# Environment variables that must be set to run this script:
# - RCLOUD_REMOTE_NAME
# - BORG_PASSPHRASE
# - BORG_EXCLUDEFILE       # (optional, if you want to skip files)
# - AWS_ACCESS_KEY_ID      # (if AWS is used)
# - AWS_SECRET_ACCESS_KEY  # (if AWS is used)
# - AWS_BUCKET_NAME        # (if AWS is used)

# Configuration
RCLOUD_CONFIG="/var/backup/config"
BORG_ARCHIVE="/var/backup/snapshots"
BORG_PATH_TO_BACKUP="/mnt/source"
export BORG_KEYS_DIR="/var/backup/keys"

# Create a snapshot
echo
echo "[BORG] Snapshot started..."

# Detect exclusion file
if [ -f "$BORG_EXCLUDEFILE" ]; then
  borg create \
    --stats \
    --progress \
    --compression zstd,22 \
    --exclude-from $BORG_EXCLUDEFILE \
    $BORG_ARCHIVE::$(date +%s) \
    $BORG_PATH_TO_BACKUP
else
  borg create \
    --stats \
    --progress \
    --compression zstd,22 \
    $BORG_ARCHIVE::$(date +%s) \
    $BORG_PATH_TO_BACKUP
fi

echo "[BORG] Snapshot completed with success!"
echo

# Uploading snapshots to rclone remote provider
echo "[RCLONE] Upload started..."
rclone sync \
  --progress \
  --config $RCLOUD_CONFIG \
  $BORG_ARCHIVE \
  $RCLOUD_REMOTE_NAME:$AWS_BUCKET_NAME
echo "[RCLONE] Upload completed with success!"
echo
